### ISSUE TITLE
Should we consider re-working the chapters map to make sure everyone is displayed by default?

### ISSUE THREAD

**Issue by rhewitt22** [maptime/maptime.github.io#136]
Right now on page load MaptimeDiliman, MaptimeJozi, and MaptimeNullIsland are not shown because we have a hard-coded value for map center and zoom.

### Option 1
Do nothing

### Option 2
Set map bounds to the bounds of chapters.json (#135).  A quick test of this zooms the map out beyond the point of having map labels, which could be undesirable. This would also ensure that all future chapters that are added to the list are in the map's initial view by default.

### Option 3
Create separate maps for the Americas, Europe, Africa, and Asia.  I don't really know what this would look like.

**Comment by geografa** [comment]
I like option 2, too.
