### ISSUE TITLE
Request to be added to MaptimeOrganization

### ISSUE THREAD

**Issue by alukach** [maptime/maptime.github.io#140]
Hi there,

Requesting to be added to the Maptime Github Organization.  I'm putting together the MaptimeCalgary (https://maptimecalgary.github.io) chapter.

Thanks.

Anthony

**Comment by lyzidiamond** [comment]
Did this happen? Can we close? @almccon @geografa @bethschechter @camilleanne

**Comment by alukach** [comment]
Yup, I was added, should have closed this myself.  Thanks!
