### ISSUE TITLE
repo for Maptime Pittsburgh

### ISSUE THREAD

**Issue by gassc** [maptime/maptime.github.io#143]
Hi! I need a repository created for the Maptime Pittsburgh site, e.g.:  **maptime / pittsburgh**

Thanks!

**Comment by lyzidiamond** [comment]
Hey @geografa has this happened yet?

**Comment by gassc** [comment]
@lyzidiamond @geografa is this something I can do? Github is new to me. I've already forked the starter template (https://github.com/gassc/pittsburgh) and created the chapter site. I just need a place to put it.

**Comment by geografa** [comment]
Sorry about that! @gassc repo is made and you have admin access. Let me know if you get stuck.

**Comment by gassc** [comment]
@geografa Thanks!
