### ISSUE TITLE
Better "Start a Chapter!" page

### ISSUE THREAD

**Issue by lyzidiamond** [maptime/maptime.github.io#153]
People get confused because our "Start a Chapter!" page just has info about getting set up on GitHub. We've talked about this before, but this page should be a request to email us to get set up, at least for now. The current page with info about getting set up on GitHub should be on GitHub, not on the website.

**Comment by bethschechter** [comment]
I agree @lyzidiamond

**Comment by geografa** [comment]
If this looks good: https://gist.github.com/geografa/de8824fd33718c9af061

I will edit this: http://maptime.io/chapters/start/ and replace with http://maptime.io/chapters/start-a-chapter/

/cc @svmatthews

**Comment by svmatthews** [comment]
@geografa once that new page is merged and running I'll fold in #177

**Comment by geobrando** [comment]
Fixed in #182
