### ISSUE TITLE
Requesting maptime/albany repo

### ISSUE THREAD

**Issue by bmcbride** [maptime/maptime.github.io#162]
@geografa, can we please get a repo added for Maptime Albany? Admins include myself (bmcbride) and  Katy DeCorah (katydecorah). Thanks!

**Comment by geografa** [comment]
@bmcbride :+1: all good. Let me know if you need help with getting the starter repo loaded in your repo. It's roughed out here: http://maptime.io/chapters/start/ /cc @katydecorah

**Comment by geografa** [comment]
On second thought - scratch those directions. They're outdated and we're changing those soon. Just lemme know if you need help with it :)

**Comment by katydecorah** [comment]
Hey there @geografa, when you get a chance can you also add `bmcbride` as an admin to the `us-ny-albany` team? Thanks!

![image](https://cloud.githubusercontent.com/assets/2180540/6831020/08c28868-d2f4-11e4-96be-d2a30f5e0967.png)

**Comment by geografa** [comment]
@katydecorah invitation is pending. @bmcbride check your email?

**Comment by katydecorah** [comment]
whoops my bad!

**Comment by bmcbride** [comment]
Sorry- been a busy morning! All set now. @katydecorah I'll get the chapter site up this evening.
