### ISSUE TITLE
is _underscore necessary anymore? 

### ISSUE THREAD

**Issue by svmatthews** [maptime/maptime.github.io#178]
Doesn't seem like we're using it any longer.

**Comment by rhewitt22** [comment]
I took a quick look and couldn't find underscore in use anywhere.  I'm pretty sure that's a leftover from the original maptime website before the move to jekyll.

**Comment by lyzidiamond** [comment]
I don't think we're using it anymore... feel free to remove @svmatthews.

**Comment by rhewitt22** [comment]
Underscore was being used to render the list of follower from github.  I just used it again to render a template of upcoming events in a new feature.  Closing.

**Comment by svmatthews** [comment]
Nice. :+1: Good find!
