### ISSUE TITLE
Better links to "Start a chapter"

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime.github.io#187]
* From what I can see you can only navigate to [Start a chapter ](http://maptime.io/start/) using the inconspicuous button at http://maptime.io/chapters/  

![start-screenshot2](https://cloud.githubusercontent.com/assets/1833870/7539516/8368aae0-f575-11e4-8095-5c5bf4f3c221.png)  

  
* This should be easier to find.  Suggest that we take out the following text at the bottom of `/chapters` since we're not really encouraging folks to use hello@maptime.io to start a chapter.  Then add a more prominent link at the top of the page, perhaps even something directly on the main page. It could alternatively replace "Maptime Summit!" on the nav bar once that is over.

![start-screenshot](https://cloud.githubusercontent.com/assets/1833870/7539606/274f986c-f576-11e4-8ade-7acf34f6ef52.png)

**Comment by svmatthews** [comment]
# DO IT NOW!

**Comment by bethschechter** [comment]
agweed

On Fri, May 8, 2015 at 9:30 AM, Sam Matthews <notifications@github.com>
wrote:

> DO IT NOW!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maptime/maptime.github.io/issues/187#issuecomment-100287708>
> .
>



-- 
@bethschechter
Maptime <http://maptime.io/> founder
ATL –> SF –> PDX

**Comment by geobrando** [comment]
![Do it!](http://i.giphy.com/wi8Ez1mwRcKGI.gif)
