### ISSUE TITLE
Markercluster style on clusters >10

### ISSUE THREAD

**Issue by lyzidiamond** [maptime/maptime.github.io#195]
When the clustering goes beyond ten, the styling is no longer applied to the markerclusters for the chapter map -- it defaults to its original styling.

![screen shot 2015-06-03 at 9 20 31 am](https://cloud.githubusercontent.com/assets/2523165/7965412/26dc7f10-09d2-11e5-98d9-2812d3e00984.png)

/cc @geografa

**Comment by rhewitt22** [comment]
@lyzidiamond @geografa 

Just need to add styles for the class `.marker-cluster-medium` to [chapters.css](https://github.com/maptime/maptime.github.io/blob/master/css/chapters.css)

Preference on color?

**Comment by geografa** [comment]
Darker hue?

**Comment by rhewitt22** [comment]
Closed by #196
