### ISSUE TITLE
Jobs page

### ISSUE THREAD

**Issue by lyzidiamond** [maptime/maptime.github.io#2]
There should be a place where maptimers can post jobs or where people who are hiring can find maptimers!

**Comment by rhewitt22** [comment]
The switchboard has started to see a lot more action.  The only link I see is on the Resources page.  Is that sufficient? Can we close @lyzidiamond ?

**Comment by geografa** [comment]
Agreed. two things: 

1. We can add a widget to the maptime hq site listing latest posts. 
1. I'd like to find out more about successes so we can promote its efficacy and keep the ball rolling.

**Comment by rhewitt22** [comment]
@geografa is there an API?

**Comment by geografa** [comment]
@rhewitt22 if there is, it's not public yet. I'm asking.

**Comment by lyzidiamond** [comment]
This is not being worked on, so closing -- feel free to reopen if someone wants to work on it.
