### ISSUE TITLE
HTML validation errors

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime.github.io#226]
Adding Travis CI and an HTML validator uncovered some site issues.  Most low priority but there were some broken links and images from older posts that could be fixed.

https://travis-ci.org/maptime/maptime.github.io/builds/77784274

**Comment by geografa** [comment]
Nice catch @geobrando . is there a clean way to kick out the errors to make a hit list for broken links to fix?

**Comment by geobrando** [comment]
I thought about that. No automated way I could find. We could export to a
text file and parse it but it should be easy enough to just copy and paste
some of the important stuff. Many of the errors are found on multiple pages
are caused by the same code since they're built using a template.

**Comment by geobrando** [comment]
@geografa In #227 I was able to fix all of these except for

1. A couple of broken image links in a post from the Wordpress days
1. Broken link to a blog post that didn't seem to get migrated from Wordpress
1. An HTML validation error which is not really an error but I was unable to get html-proofer to ignore as described in https://github.com/gjtorikian/html-proofer/issues/233

https://travis-ci.org/maptime/maptime.github.io/builds/77983913
