### ISSUE TITLE
Maptime stickers!

### ISSUE THREAD

**Issue by mnorelli** [maptime/maptime.github.io#287]
I thought this might fit into Lessons and Resources under the Community heading?  Maybe as:

<a href="https://www.stickermule.com/marketplace/10198-maptime-sticker">Maptime Stickers</a>  Kit out your next Maptime event with official stickers!

Feel free to shunt elsewhere or to elsewhom it may interest.  But that link would be helpful on the site.

UPDATE (3/2019):  The StickerMule link above which included the path to the Maptime art is no longer working.  Follow almccon's advice below to make stickers from a supplier of your choice.

**Comment by almccon** [comment]
ALSO! There is the original design for the sticker in this repo: https://github.com/maptime/maptime-logo/tree/gh-pages/illustrator If you want to use that to try to get a better deal on a larger run of stickers.

StickerMule is nice and all, and they do get cheaper if you order larger amounts, but if you're already making the effort to order a ton of stickers, you might get slightly better quality if you use someone other than StickerMule.
