### ISSUE TITLE
Enable (and force) HTTPS

### ISSUE THREAD

**Issue by jbelien** [maptime/maptime.github.io#297]
Hello,

Would it be possible to enable (and force) HTTPS for 🇧🇪  http://maptime.io/belgium/ (and all the other repos) now that GitHub Pages provides free SSL certificate ?

Thanks a lot 🎉

**Comment by jbelien** [comment]
Anyone still around ? 😄

**Comment by geobrando** [comment]
@jbelien  I saw you ended up transferring your content but action @jenningsanderson took in https://github.com/maptime/maptime-admin/issues/266 enabled HTTPS.  I believe you can go in to the settings for your chapter repo and check the box in the Pages section to enforce HTTPS on your pages.

**Comment by jbelien** [comment]
@geobrando Excellent news that Maptime is making a comeback!

>  I believe you can go in to the settings for your chapter repo and check the box in the Pages section to enforce HTTPS on your pages.

I don't have admin rights on https://github.com/maptime/belgium so I can't access the Pages settings.
