### ISSUE TITLE
MaptimeATL chapter page

### ISSUE THREAD

**Issue by rhewitt22** [maptime/maptime.github.io#57]
Hacking on our chapter page

- [ ] Header image
- [ ] First blog post -- recap of first meeting?

cc @landonreed

**Comment by geografa** [comment]
@landonreed  @rhewitt hey y'all. What's the status of this? Did you guys never get a repo?

**Comment by rhewitt** [comment]
Hi, this isn't one of my projects. Looks like you might have intended user rhewitt22. 


     On Tuesday, March 24, 2015 8:46 PM, geografa <notifications@github.com> wrote:
   

 @landonreed @rhewitt hey y'all. What's the status of this? Did you guys never get a repo? —

**Comment by geografa** [comment]
zoops! sorry about that.

**Comment by rhewitt22** [comment]
@geografa This has been in purgatory for a while.  I just took a new job and moved so I've been pretty stacked up and haven't had much time to think about Maptime as I would like.

**Comment by geografa** [comment]
@rhewitt22 I hear that. Let me know if someone jumps in.

**Comment by landonreed** [comment]
Nice one, Roy!  Congrats on the new job.

Yea, I don't think I have the time/brain space to pull off MaptimeATL
solo.  Roy, let me know if your life becomes less hectic and we can meet up
again and plan future events.


---
Landon Reed  | http://landonreed.net
@eltiar <https://twitter.com/eltiar>

**Comment by rhewitt22** [comment]
@landonreed I just moved last weekend to old fourth ward and took the web dev position with the Fish & Wildlife Service.  We're getting settled so I should be able to come up for air in the next couple of weeks!

**Comment by lyzidiamond** [comment]
@bethschechter weren't there some other interested folks in the Atlanta area who you knew? Or am I crazy?

**Comment by rhewitt** [comment]
Hi, Could you drop me from the cc's?
Thanks,Robin
 


     On Monday, March 30, 2015 11:48 AM, Lyzi Diamond <notifications@github.com> wrote:
   

 @bethschechter weren't there some other interested folks in the Atlanta area who you knew? Or am I crazy?—

**Comment by geografa** [comment]
Really sorry about this, Robin. Not sure if we can do this on our end but you can unsubscribe from clicking the 'Unsubscribe' button like this:
![maptimeatl_chapter_page_ _issue__57_ _maptime_maptime_github_io](https://cloud.githubusercontent.com/assets/134753/6910249/9a3c08b8-d705-11e4-8ba0-0f59b4c2b0f2.png)

**Comment by geobrando** [comment]
So is MaptimeATL willing and able to host a site at maptime.io and do you want the starter template?  If so, I'll create an `atlanta` repo and clone it for you.  @rhewitt22 @landonreed @RRLash @mollietaylor

**Comment by rhewitt22** [comment]
I was planning on just doing a directory inside of the maptime.io

Roy

**Comment by geobrando** [comment]
Hey @rhewitt22 ... We decided not to do any more chapter pages as folders in maptime.github.io.  I think you probably have push privileges there but most don't, and so now we're letting people manage their own sites as separate repos.

**Comment by geobrando** [comment]
@rhewitt22  Went ahead and created an Atlanta repo.  Your point is well taken about aggregating posts on the homepage and is something that's being discussed at maptime/maptime-admin#50.  Separate repos makes that more challenging but the thought was that chapter pages in folders puts more of a burden on those with admin privileges as it requires merging pull requests.

If you'd rather host a site under your existing maptimeatl org we can just delete it.
