### ISSUE TITLE
Fix overflow on marker popup

### ISSUE THREAD

**Issue by geografa** [maptime/maptime.github.io#98]
chapter titles stretch beyond popup wrapper
![screen shot 2014-10-26 at 1 10 09 am](https://cloud.githubusercontent.com/assets/134753/4782248/a4e05a82-5ce7-11e4-8e99-3808f0c533cb.png)

**Comment by uafrazier** [comment]
In Leaflet, the maxWidth option of L.popup is 300 by default.

I fixed this issue in my fork by modifying chapters.js.  I just passed a larger maxWidth option to the bindPopup() method of the chapterMarkers variable like so:

```javascript
   var chapterMarkers = L.geoJson( data, {
      onEachFeature: function (feature, layer) {
	    var popupOptions = {'maxWidth' : '1000'};  
        var popupContent = '<h2>'+ feature.properties.title +'</h2>' + 'Twitter: ' + 
          '<a href="http://twitter.com/' + feature.properties.twitter + '" target="_blank">@' + feature.properties.twitter +'</a>';
        layer.bindPopup(popupContent,popupOptions);
        layer.setIcon(new L.Icon({
          iconUrl:'/img/maptime-marker.png',
          iconSize: [24,24],
          iconAnchor: [6,12],
          popupAnchor: [5,-10]
        }));
      }
    });
```

If acceptable solution, I can send pull request.

![nooverflow](https://cloud.githubusercontent.com/assets/1992577/5893183/423ccb6e-a4a8-11e4-8415-f21293ecf6f1.png)

**Comment by geografa** [comment]
@uafrazier looks good! Send it in :)

**Comment by geografa** [comment]
fixed
